### ISSUE TITLE
N.T.O.S. Button Goes to a Restricted Page

### ISSUE THREAD

**Issue by jlefkoff** [Raajheer1/IDS#23]
As a non TMU staff, I do not have access to the NTOS vatusa [page](https://www.vatusa.net/mgt/tmu#notices). Consider removing this functionality unless a user has access to the page (S3 or higher?)

**Comment by Raajheer1** [comment]
I think it's only ARTCC staff that has permission to view the page. I'm not entirely sure, maybe that is something VATUSA can change. Nothing I can do on my end.
